[general]
import = ["~/.config/alacritty/themes/apex-neon.toml"]

live_config_reload = true
ipc_socket = true

[window]
opacity = 0.7
padding = { x = 4, y = 4 }

[font]
normal = { family = "Inconsolata Nerd Font Mono", style = "Regular" }
size = 9

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Beam", blinking = "Off" }
